name: CLEAN
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup client
        run: |
          curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux-dev.tgz | sudo tar -zxvf- -C /usr/local/bin
          testspace config url https://$TESTSPACE_TOKEN:@s2.$TESTSPACE_DOMAIN.com
      - name: Clean out failure tracking
        run: |
          ./push.clean.sh